### ISSUE TITLE
Division by zero if all function values are the same 

### ISSUE THREAD

**Issue by matthias-mayr** [luinardi/hypermapper#30]
I just ran some experiments to find a memory leak in and replaced the actual function call with a mockup that always returns the same value.
So in the DOE phase, I'd return some different parameter configurations, all with the same function value to hypermapper. For example:
```
Response:
x0,x1,x2,x3,x4,x5,reward,
0.9218301621703393,1.588079988886741,1.214550992612109,-0.07458819627960911,-0.930087999361561,-1.5026907805108718,-2
1.0572519949789458,0.12629581444216464,-1.705693133127367,-1.344143676922643,1.9071547853739172,0.5905048498061332,-2
[...]
```
This leads to this error:
```
 /home/matthias/.local/lib/python3.6/site-packages/GPy/util/normalizer.py:96: RuntimeWarning:invalid value encountered in true_divide
Traceback (most recent call last):
  File "/home/matthias/Workspaces/hypermapper/scripts/hypermapper.py", line 87, in <module>
    optimize(parameters_file)
  File "/home/matthias/Workspaces/hypermapper/scripts/hypermapper.py", line 56, in optimize
    bo.main(config, black_box_function=black_box_function)
  File "/home/matthias/Workspaces/hypermapper/scripts/bo.py", line 321, in main
    classification_model)
  File "/home/matthias/Workspaces/hypermapper/scripts/random_scalarizations.py", line 392, in random_scalarizations
    previous_points=data_array)
  File "/home/matthias/Workspaces/hypermapper/scripts/local_search.py", line 295, in local_search
    function_values_uniform, feasibility_indicators_uniform = optimization_function(configurations=uniform_configurations, **optimization_function_parameters)
  File "/home/matthias/Workspaces/hypermapper/scripts/random_scalarizations.py", line 91, in run_acquisition_function
    number_of_cpus)
  File "/home/matthias/Workspaces/hypermapper/scripts/random_scalarizations.py", line 316, in EI
    /(tmp_objective_limits[objective][1] - tmp_objective_limits[objective][0])
ZeroDivisionError: float division by zero
```
In my opinion this case should be covered by hypermapper. Especially if only D+1 samples are used in the DOE phase, there is a chance that the function values are the same.

(For my small debugging experiments, I just replace the constant value with a random number.)

**Comment by arturluis** [comment]
Hi @matthias-mayr, 

Thanks for reporting this, I have just pushed a fix for this issue. Let me know if the error persists.
