### ISSUE TITLE
v2.2 breaks usage from C++ client

### ISSUE THREAD

**Issue by matthias-mayr** [luinardi/hypermapper#34]
I am using hypermapper from a C++ client. Since version 2.2, I am receiving these errors:

```
Executing command: python3 /home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py /tmp/blackdrops/iiwa_skills_peg/20210220-172252_5_params/optimizations/scenario_0.json
/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py:10: UserWarning: 
        *****
        HyperMapper seems to have been imported as a module.
        This might lead to errors.
        Please be sure that you want to do this.
        Otherwise, this is probably caused by a misconfiguration of HyperMapper when trying to execute an example.
        Please choose one of the following options to fix this issue.
        1) (recommended)
                * Remove '.../hypermapper/scripts' from your PYTHONPATH.
                * Run your example from the HyperMapper root directory with 'python -m dir1.dir2.yourexample'
        2)
                * Update your PYTHONPATH from '.../hypermapper/scripts' to '.../hypermapper'.
                * Run your script as before.
        *****
  "\n\t*****\n\tHyperMapper seems to have been imported as a module.\n\tThis might lead to errors.\n\t"
/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py:42: UserWarning: Found hypermapper in PYTHONPATH. Usage is deprecated and might break things. Please remove all hypermapper references from PYTHONPATH. Trying to import without hypermapper in PYTHONPATH...
  "Found hypermapper in PYTHONPATH. Usage is deprecated and might break things. "
Traceback (most recent call last):
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py", line 22, in <module>
    from hypermapper import optimizer
ImportError: cannot import name 'optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py", line 22, in <module>
    from hypermapper import optimizer
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py", line 59, in <module>
    from hypermapper import optimizer
ImportError: cannot import name 'optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/scripts/hypermapper.py", line 59, in <module>
    from hypermapper import optimizer
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/__init__.py", line 12, in <module>
    from . import plot_hvi  # noqa
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/plot_hvi.py", line 73, in <module>
    import statsmodels.stats.api as sms
ModuleNotFoundError: No module named 'statsmodels'
```

My `PYTHONPATH`: `/home/ubuntu/Workspaces/blackdrops_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages`
My `HYPERMAPPER_HOME`: `/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper`

Measures taken:
- delete pyc files
- tried calling `hypermapper/optimizer.py` directly, which leads to these errors:

```
python3 /home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/optimizer.py /tmp/blackdrops/iiwa_skills_peg/20210220-170230_5_params/optimizations/scenario_0.json
Traceback (most recent call last):
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/optimizer.py", line 12, in <module>
    from hypermapper import bo
ModuleNotFoundError: No module named 'hypermapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/optimizer.py", line 52, in <module>
    from hypermapper import bo
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/__init__.py", line 12, in <module>
    from . import plot_hvi  # noqa
  File "/home/ubuntu/Workspaces/blackdrops_ws/src/blackdrops/deps/hypermapper/hypermapper/plot_hvi.py", line 73, in <module>
    import statsmodels.stats.api as sms
ModuleNotFoundError: No module named 'statsmodels'
```

**Comment by LeoIV** [comment]
Thank you for opening this issue. Regarding this lengthy warning in the first scripting: this should not be here. We have taken several precautions to allow back-compatibility of HyperMapper, but we recommend some changes in using HyperMapper now, in particular, to use it as you've done in your second scripting, i.e., to use `hypermapper/optimizer.py` directly.

To your particular problem: the wiki doesn't show `statsmodels` as a requirement but not having `statsmodels` installed broke things with release 2.2. I moved the import such that `statsmodels` is only required inside of the `plot_hvi` function. Please pull the newest version.

By the way: you can also install HyperMapper via pip: `pip install hypermapper`. That gives you a command `hypermapper` (global in your Python environment) that can be used as an alternative to calling `hypermapper/optimizer.py`

**Comment by matthias-mayr** [comment]
Thanks for the fix. I tested it and it works.

If you want to advocate to use `hypermapper/optimizer.py`, you might want to update the example client [here](https://github.com/luinardi/hypermapper/blob/02bd83b5b1d3feb9907cf1187864ded66ba2c539/example_scenarios/clients/cpp_client/cpp_client.cpp#L272) and potentially some other places as well.
